### ISSUE TITLE
Classifica

### ISSUE THREAD

**Issue by GiacomoGazzanelli** [LOASL-Cecioni/Fantacalcio2017#6]
Classifica del campionato con relativa classifica marcatori, assist e cartellini.

**Comment by marcsol99** [comment]
La classifica dovrà contenere i nomi di tutte le squadre e ordinarle in base ai punti che ottengono in seguito alle partite; sarà presente anche una classifica per marcatori (maggior numero di goal), per assist (maggior numero di assist) e per cartellni (maggior numero di cartellini).

Per realizzare una buona classifica in C++:
- [http://www.pierotofy.it/pages/extras/forum/2/1019012-programma_per_classifiche/](url)
- [http://www.cplusplus.com/doc/tutorial/files/](url)
- [https://www.iprogrammatori.it/forum-programmazione/cplusplus/gestione-campionato-calcio-t4621.html](url)
